---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

resources:
  - db

secretGenerator:
  - name: postgres
    literals:
      - password=postgres

patches:
  - target:
      kind: Deployment
      name: api-deployment
    patch: |-
      - op: add
        path: "/spec/containers/0/env"
        value:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
