---
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: python-lint
        name: Python-lint
        description: This hook runs pylint.
        entry: pylint
        language: python
        files: \.(py)$
      - id: detect-secrets
        name: Detect Secrets
        description: This hook detects and prevents high entropy strings from entering the codebase.
        entry: hooks/detect-secrets
        language: script
        files: .*
      - id: forbid-binary
        name: forbid-binary (local)
        language: script
        entry: hooks/forbid-binary
        types: ['binary']
        exclude: >
          (?x)^(
            screenshot.png
          )$
      - id: git-dirty
        name: git-dirty (local)
        language: script
        entry: hooks/git-dirty

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
