---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: labelstudio
    app.kubernetes.io/name: labelstudio
    app.kubernetes.io/version: 1.4.1
  name: labelstudio
  namespace: labelstudio
automountServiceAccountToken: false
