---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: labelstudio
    app.kubernetes.io/name: labelstudio
    app.kubernetes.io/version: 1.4.1
  name: labelstudio
  namespace: labelstudio
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: labelstudio
    app.kubernetes.io/name: labelstudio
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: labelstudiodb
    app.kubernetes.io/name: labelstudiodb
    app.kubernetes.io/version: 1.4.1
  name: labelstudiodb
  namespace: labelstudio
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/instance: labelstudiodb
    app.kubernetes.io/name: labelstudiodb
