---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: labelstudio
    app.kubernetes.io/name: labelstudio
    app.kubernetes.io/version: 1.5.0
  name: labelstudio
  namespace: labelstudio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi
  storageClassName: azurefile-labelstudio
