---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    app.kubernetes.io/instance: labelstudio
    app.kubernetes.io/name: labelstudio
    app.kubernetes.io/version: 1.5.0
  name: depttls
  namespace: labelstudio
spec:
  provider: azure
  secretObjects:
    - secretName: ingress-tls-csi
      type: kubernetes.io/tls
      data:
      - objectName: deptexample
        key: tls.key
      - objectName: deptexample
        key: tls.crt
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ~
    keyvaultName: ~
    objects: |
      array:
        - |
          objectName: deptexample
          objectType: secret
    tenantId: ~
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    app.kubernetes.io/instance: labelstudio
    app.kubernetes.io/name: labelstudio
    app.kubernetes.io/version: 1.5.0
  name: labelstudio
  namespace: labelstudio
spec:
  provider: azure
  secretObjects:
    - secretName: labelstudio
      type: Opaque
      data:
        - objectName: PGSQLPASSWORD
          key: POSTGRE_PASSWORD
        - objectName: LSPASSWORD
          key: LABEL_STUDIO_PASSWORD
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ~
    keyvaultName: ~
    objects: |
      array:
        - |
          objectName: PGSQLPASSWORD
          objectType: secret
        - |
          objectName: LSPASSWORD
          objectType: secret
    tenantId: ~
