---
namespace: monitoring

bases:
  - base/namespace.yaml


resources:
  # - github.com/prometheus-operator/kube-prometheus?ref=v0.11.0
  - resources/0crd-alertmanagerconfigs.yaml
  - resources/0crd-alertmanagers.yaml
  - resources/0crd-podmonitors.yaml
  - resources/0crd-probes.yaml
  - resources/0crd-prometheuses.yaml
  - resources/0crd-prometheusrules.yaml
  - resources/0crd-servicemonitors.yaml
  - resources/0crd-thanosrulers.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 39.12.1
    releaseName: monitoring
    namespace: monitoring
    valuesFile: values.yaml
