---
namespace: monitoring

bases:
  - base/namespace.yaml


resources:
  # - github.com/prometheus-operator/kube-prometheus?ref=v0.11.0
  - resources/0alertmanagerConfigCustomResourceDefinition.yaml
  - resources/0alertmanagerCustomResourceDefinition.yaml
  - resources/0podmonitorCustomResourceDefinition.yaml
  - resources/0probeCustomResourceDefinition.yaml
  - resources/0prometheusCustomResourceDefinition.yaml
  - resources/0prometheusruleCustomResourceDefinition.yaml
  - resources/0servicemonitorCustomResourceDefinition.yaml
  - resources/0thanosrulerCustomResourceDefinition.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 39.12.1
    releaseName: monitoring
    namespace: monitoring
