---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - https://github.com/prometheus-operator/prometheus-operator/releases/latest/download/bundle.yaml
  - namespace.yaml
