# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/Users/imjoseangel/playground/imjoseangel/sandbox/terraform/terragrunt/envs/dev/pas/terraform.tfstate"
  }
}
