---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: azurefile-airflow
mountOptions:
- mfsymlinks
- actimeo=30
parameters:
  skuName: Standard_LRS
  resourceGroup: airflow-rsg
  storageAccount: airflowst
provisioner: file.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
