apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  image: rabbitmq:3.10.2-management
  resources:
    requests:
      cpu: '1'
      memory: 2Gi
    limits:
      cpu: '2'
      memory: 5Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
      ssl_options.verify = verify_peer
      ssl_options.fail_if_no_peer_cert = true
      load_definitions = /mnt/configuration/definitions.json
    additionalPlugins:
      - rabbitmq_tracing
      - rabbitmq_shovel
      - rabbitmq_shovel_management
      - rabbitmq_federation
      - rabbitmq_federation_management
  tls:
    secretName: rabbitmq-server-certs
    caSecretName: rabbitmq-ca-cert
  persistence:
    storageClassName: managed-csi-premium
    storage: "128Gi"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - rabbitmq
          topologyKey: kubernetes.io/hostname
  override:
    statefulSet:
      spec:
        updateStrategy:
          type: RollingUpdate
        template:
          spec:
            nodeSelector:
              agentpool: ~
              kubernetes.io/os: linux
            tolerations:
              - effect: NoSchedule
                key: RabbitMQOnly
                operator: Equal
                value: "true"
            containers:
              - name: rabbitmq
                volumeMounts:
                  - mountPath: /mnt/secrets/ingress-tls
                    name: ingress-tls
                  - mountPath: /mnt/secrets/rabbitmq-certs
                    name: rabbitmq-certs
                  - mountPath: /mnt/configuration/
                    name: definitions
            volumes:
              - name: ingress-tls
                csi:
                  driver: secrets-store.csi.k8s.io
                  readOnly: true
                  volumeAttributes:
                    secretProviderClass: ingress-tls
              - name: rabbitmq-certs
                csi:
                  driver: secrets-store.csi.k8s.io
                  readOnly: true
                  volumeAttributes:
                    secretProviderClass: rabbitmq-certs
              - name: definitions
                configMap:
                  name: definitions
            topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: "topology.kubernetes.io/zone"
                whenUnsatisfiable: DoNotSchedule
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: rabbitmq
