apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
spec:
  selector:
    app: webapp
    version: v1
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32001
