---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v2
  labels:
    app: webapp
    version: v2
spec:
  selector:
    matchLabels:
      app: webapp
      version: v2
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp
        version: v2
    spec:
      containers:
      - name: webapp
        image: yaiiteng/my-nginx:v2
        ports:
        - containerPort: 80
        resources: {}
