---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
  labels:
    app: webapp
    version: v1
spec:
  selector:
    matchLabels:
      app: webapp
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      containers:
      - name: webapp
        image: yaiiteng/my-nginx:v1
        ports:
        - containerPort: 80
        resources: {}
