---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tls
  namespace: airflow
spec:
  provider: azure
  secretObjects:
    - secretName: ingress-tls-csi
      type: kubernetes.io/tls
      data:
      - objectName: tls
        key: tls.key
      - objectName: tls
        key: tls.crt
    - secretName: az-tenant-id
      type: Opaque
      data:
        - objectName: AZTENANTID
          key: AZURE_TENANT_ID
    - secretName: az-client-id
      type: Opaque
      data:
        - objectName: AZCLIENTID
          key: AZURE_CLIENT_ID
    - secretName: az-client-secret
      type: Opaque
      data:
        - objectName: AZCLIENTSECRET
          key: AZURE_CLIENT_SECRET
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 00000000-0000-0000-0000-000000000000
    keyvaultName: mykv
    objects: |
      array:
        - |
          objectName: tls
          objectType: secret
        - |
          objectName: AZTENANTID
          objectType: secret
        - |
          objectName: AZCLIENTID
          objectType: secret
        - |
          objectName: AZCLIENTSECRET
          objectType: secret
    tenantId: 00000000-0000-0000-0000-000000000000
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: airflow-secrets
  namespace: airflow
spec:
  provider: azure
  secretObjects:
    - secretName: airflow-metadata
      type: Opaque
      data:
        - objectName: airflowdbconn
          key: connection
    - secretName: airflow-result-backend
      type: Opaque
      data:
        - objectName: airflowdbresultconn
          key: connection
    - secretName: webserver-secret-key
      type: Opaque
      data:
        - objectName: airflowwebserversecretkey
          key: webserver-secret-key
    - secretName: fernet-key
      type: Opaque
      data:
        - objectName: airflowfernetkey
          key: fernet-key
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 00000000-0000-0000-0000-000000000000
    keyvaultName: mykv
    objects: |
      array:
        - |
          objectName: airflowdbconn
          objectType: secret
        - |
          objectName: airflowdbresultconn
          objectType: secret
        - |
          objectName: airflowwebserversecretkey
          objectType: secret
        - |
          objectName: airflowfernetkey
          objectType: secret
    tenantId: 00000000-0000-0000-0000-000000000000
