---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api
  - db

commonLabels:
  sandbox: dev

commonAnnotations:
  logging: verbose

namespace: sandbox

namePreffix: myapp-
nameSuffix: -dev

images:
  - name: mongo
    newName: postgres
    newTag: '4.2'

patches:
  - target:
      kind: Deployment
      name: api-deployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: web-deployment
