---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base
  - api
  - db

components:
  - components

labels:
  - includeSelectors: false
    pairs:
      sandbox: dev

commonAnnotations:
  logging: verbose

namespace: sandbox

namePrefix: myapp-
nameSuffix: -dev

images:
  - name: mongo
    newName: postgres
    newTag: '4.2'

patches:
  - target:
      kind: Deployment
      name: api-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-deployment
      spec:
        replicas: 5

  - target:
      kind: Deployment
      name: api-deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/-
        value:
          name: nginx
          image: nginx

  - target:
      kind: Deployment
      name: api-deployment
    patch: |-
      - op: remove
        path: /spec/template/metadata/labels/sandbox

configMapGenerator:
  - name: db-cred
    behavior: merge
    literals:
      - password=mypassword
  - name: nginx-config
    behavior: replace
    files:
      - nginx.conf
    options:
      labels:
        app-config: my-config

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app-config: my-config
  annotations:
    myannotation: othervalue
