---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api
  - db

commonLabels:
  org: imjoseangel

commonAnnotations:
  logging: verbose

namespace: sandbox

namePreffix: myapp-
nameSuffix: -dev

images:
  - name: mongo
    newName: postgres
    newTag: '4.2'
