---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minikube
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
provisioner: k8s.io/minikube-hostpath
allowVolumeExpansion: false
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - actimeo=30
