---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
spec:
  destination:
    namespace: keda
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kedacore.github.io/charts'
    targetRevision: 2.7.2
    chart: keda
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
