---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: k8sexample
  name: k8sexample
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: k8sexample
    app.kubernetes.io/name: k8sexample
  name: k8sexample
  namespace: k8sexample
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 2
  labels:
    app.kubernetes.io/instance: k8sexample
    app.kubernetes.io/name: k8sexample
  name: k8sexample
  namespace: k8sexample
spec:
  serviceName: "k8sexample"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: k8sexample
      app.kubernetes.io/name: k8sexample
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: k8sexample
        app.kubernetes.io/name: k8sexample
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: '2'
      serviceAccountName: k8sexample
      containers:
        - image: imjoseangel/k8stest:latest
          imagePullPolicy: Always
          name: k8sexample
          ports:
            - containerPort: 8080
              name: k8sexample
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          resources:
            requests:
              cpu: 125m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          securityContext:
            allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: k8sexample
    app.kubernetes.io/name: k8sexample
  name: k8sexample
  namespace: k8sexample
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: k8sexample
    app.kubernetes.io/name: k8sexample
