---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 125m
            memory: 250Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      tolerations:
        - effect: NoSchedule
          key: HighMemOnly
          operator: Equal
          value: "true"
      nodeSelector:
        kubernetes.io/os: windows
