import os

from google import genai
import numpy as np

api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    raise RuntimeError("GEMINI_API_KEY must be set before running this script.")
client = genai.Client(api_key=api_key)


def l2_normalize(vec: np.ndarray) -> np.ndarray:
    norm = np.linalg.norm(vec)
    if norm == 0:
        return vec
    return vec / norm


def format_doc(text: str, title: str = "none") -> str:
    return f"title: {title} | text: {text}"


def format_query(text: str) -> str:
    return f"task: search result | query: {text}"


# Comprehensive test corpus with multiple topics and hard negatives
corpus = [
    # AI & Embeddings
    (
        "Gemini Embedding 2 accepts text, image, audio, and video inside a"
        " 3072-dimension space."
    ),
    (
        "Matryoshka representation learning bundles key conceptual signals"
        " into the earliest vector positions."
    ),
    ("Gemini 3.8 Flash introduces deep reasoning and 1M token context" + " capacity."),
    (
        "Text-embedding-004 is an older text-only embedding model that outputs"
        " 768-dimension vectors."
    ),
    (
        "Gemini 1.5 Pro features a 2M token context window specialized for large"
        " multimodal context understanding."
    ),
    # Databases & Vector Indexing
    (
        "PostgreSQL pgvector accelerates nearest neighbor lookups using HNSW"
        + " indexes."
    ),
    (
        "Qdrant and Pinecone provide managed vector databases with native"
        " payload filtering and scalar quantization."
    ),
    (
        "Relational databases use B-Trees for structured range queries, which"
        " do not support high-dimensional semantic search."
    ),
    # Coffee & Beverages (Distractors)
    (
        "Cold brew coffee requires coarse grind sizes and long steeping"
        " windows of 12 to 24 hours."
    ),
    (
        "Espresso brewing relies on finely ground coffee and high pressure (9"
        " bars) for rich extraction."
    ),
    # Science & Astronomy (Distractors)
    (
        "The James Webb Space Telescope uses high-resolution infrared detectors"
        " to capture the earliest galaxies."
    ),
    (
        "LIGO detected gravitational waves generated by merging binary black"
        " holes millions of light-years away."
    ),
]


def ingest_corpus(docs: list[str]) -> list[dict]:
    """Ingests text documents into dual-resolution vector representations."""
    print(f"Ingesting {len(docs)} documents into dual-resolution store...")
    documents = []
    for document_id, text in enumerate(docs):
        response = client.models.embed_content(
            model="gemini-embedding-2", contents=format_doc(text)
        )
        if not response.embeddings:
            raise RuntimeError("Embedding response did not contain any embeddings.")
        full_vec = np.array(response.embeddings[0].values, dtype=np.float32)
        short_vec = l2_normalize(full_vec[:768])
        documents.append(
            {
                "id": document_id,
                "text": text,
                "full_vector": full_vec,
                "short_vector": short_vec,
            }
        )
    print("Ingestion complete.\n")
    return documents


def two_stage_search(
    search_query: str,
    documents: list[dict],
    top_k_coarse: int = 5,
    top_k_final: int = 3,
) -> tuple[list[tuple[int, float]], list[tuple[int, float]]]:
    """Performs coarse search on 768 dims followed by fine rescore on 3072 dims."""
    # Embed query
    query_resp = client.models.embed_content(
        model="gemini-embedding-2", contents=format_query(search_query)
    )
    if not query_resp.embeddings:
        raise RuntimeError("Query embedding response did not contain an embedding.")
    query_full = np.array(query_resp.embeddings[0].values, dtype=np.float32)
    query_short = l2_normalize(query_full[:768])

    # Stage 1: Fast coarse retrieval (768 dimensions across all documents)
    stage1_scores = []
    for document in documents:
        similarity = float(np.dot(query_short, document["short_vector"]))
        stage1_scores.append((document["id"], similarity))
    stage1_scores.sort(key=lambda item: item[1], reverse=True)
    candidate_pool = stage1_scores[:top_k_coarse]

    # Stage 2: Fine rescore (3072 dimensions only on candidate pool)
    stage2_scores = []
    for document_id, _ in candidate_pool:
        full_score = float(np.dot(query_full, documents[document_id]["full_vector"]))
        stage2_scores.append((document_id, full_score))
    stage2_scores.sort(key=lambda item: item[1], reverse=True)
    final_pool = stage2_scores[:top_k_final]

    return candidate_pool, final_pool


def main() -> None:
    documents = ingest_corpus(corpus)

    test_queries = [
        "What are the multimodal capabilities and vector dimensions of Gemini Embedding 2?",
        "How do HNSW index structures improve vector search performance in PostgreSQL?",
        "Why is coarse grinding important when steeping cold brew coffee?",
        "Which telescope observes the early universe using infrared instruments?",
    ]

    for i, test_query in enumerate(test_queries, 1):
        print("============================================================")
        print(f'Test Query {i}: "{test_query}"')
        print("============================================================")

        coarse_matches, rescored_matches = two_stage_search(
            search_query=test_query,
            documents=documents,
            top_k_coarse=4,
            top_k_final=2,
        )

        print("\n[Stage 1: Top Candidates via 768-d Fast Scan]")
        for rank, (document_id, similarity) in enumerate(coarse_matches, 1):
            print(
                f"  {rank}. (Score: {similarity:.4f}) "
                f"{documents[document_id]['text']}"
            )

        print("\n[Stage 2: Final Top 2 Rescored via 3072-d]")
        for rank, (document_id, similarity) in enumerate(rescored_matches, 1):
            print(
                f"  {rank}. (Score: {similarity:.4f}) "
                f"{documents[document_id]['text']}"
            )
        print()


if __name__ == "__main__":
    main()
