version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - ./nginx/html/:/etc/nginx/html
    ports:
      - 80:80
      - 443:443

  frontend:
    image: nginx:latest
    container_name: frontend
    expose:
      - "80"

  api:
    image: imjoseangel/restapi:latest
    container_name: api
    expose:
      - "5000"
