---
applications:
  - name: Test Application 1
    location: westeurope
    url: https://www.example.com
    time: 10
  - name: Test Application 2
    location: westeurope
    url: https://www.google.com
    time: 10
