apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: coinflip-
spec:
  entrypoint: coinflip
  templates:
  - name: coinflip
    steps:
    # flip a coin
    - - name: flip-coin
        template: flip-coin
    # evaluate the result in parallel
    - - name: create-regex
        template: create                       # call create template if ~ "hea"
        when: "'{{steps.flip-coin.outputs.result}}' =~ '.*0 to destroy.*'"
      - name: destroy-regex
        template: destroy                       # call create template if ~ "tai"
        when: "'{{steps.flip-coin.outputs.result}}' =~ '.*1 to destroy.*'"

  # Return create or destroy based on a random number
  - name: flip-coin
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result = "0 to destroy" if random.randint(0,1) == 0 else "1 to destroy"
        print(result)

  - name: create
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"0 to destroy\""]

  - name: destroy
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"1 to destroy\""]
