---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app.kubernetes.io/name: microservice
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservice
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: '2'
      serviceAccountName: microservice
      containers:
      - image: microservice
        imagePullPolicy: IfNotPresent
        name: microservice
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: 125m
            memory: 125Mi
          limits:
            cpu: 750m
            memory: 768Mi
        securityContext:
          allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/os: linux
