---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - prometheus.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
