# Generated by Django 4.0.8 on 2022-12-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
