---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudprobe
  labels:
    app.kubernetes.io/name: prometheus
spec:
  selector:
    matchLabels:
      app: cloudprober
  endpoints:
  - port: web
