# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

import logging
import sys
from azure.identity import DefaultAzureCredential
from azure.mgmt.sql import SqlManagementClient

"""
# PREREQUISITES
    pip install azure-identity
    pip install azure-mgmt-sql
# USAGE
    python create_database_copy_mode.py

    Before run the sample, please set the values of the client ID, tenant ID and client secret
    of the AAD application as environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID,
    AZURE_CLIENT_SECRET. For more info about how to get the value, please see:
    https://docs.microsoft.com/azure/active-directory/develop/howto-create-service-principal-portal
"""


def main():

    logging.basicConfig(format="%(asctime)s - %(levelname)-8s - %(name)s - %(message)s",
                        datefmt="%d-%m-%y %H:%M:%S",
                        stream=sys.stdout,
                        level=logging.INFO)

    client = SqlManagementClient(
        credential=DefaultAzureCredential(),
        subscription_id="e20530ac-35af-408a-a2bf-2f1a1df9086c",
    )

    version = "v0.0.2"
    response = client.databases.begin_create_or_update(
        resource_group_name="sbx-neu-dev-jam-rg",
        server_name="sbx-neu-dev-jam-sql",
        database_name=f"sbx-neu-dev-jam-sql_{version}",
        parameters={
            "location": "northeurope",
            "properties": {
                "createMode": "Copy",
                "sourceDatabaseId": "/subscriptions/e20530ac-35af-408a-a2bf-2f1a1df9086c/resourceGroups/sbx-neu-dev-jam-rg/providers/Microsoft.Sql/servers/sbx-neu-dev-jam-sql/databases/sbx-neu-dev-jam-sql_v0.0.1",
            },
            "sku": {"name": "GP_S_Gen5", "tier": "GeneralPurpose", "family": "Gen5", "capacity": 1},
        },
    ).result()
    print(response)


# x-ms-original-file: specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/examples/CreateDatabaseCopyMode.json
if __name__ == "__main__":
    main()
